# Generated by Django 5.0.3 on 2024-03-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('notation', models.CharField(max_length=1)),
                ('key', models.CharField(max_length=3)),
                ('time', models.CharField(max_length=3)),
                ('notes', models.CharField(max_length=5000)),
                ('tablature', models.CharField(max_length=1)),
                ('clef', models.CharField(max_length=10)),
                ('tuning', models.CharField(max_length=8)),
                ('tab_stems', models.CharField(max_length=1)),
                ('tab_stems_direction', models.CharField(max_length=2)),
                ('author', models.CharField(max_length=50)),
            ],
        ),
    ]
