# Generated by Django 5.0.3 on 2024-03-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytabs', '0006_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='experienceLevel',
            field=models.CharField(default='Intermediate', max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='genre1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='genre2',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
