# Generated by Django 5.0.3 on 2024-03-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytabs', '0007_userprofile_experiencelevel_userprofile_genre1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='genre3',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
