# Generated by Django 5.0.3 on 2024-03-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytabs', '0008_userprofile_genre3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='genre1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='genre2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='genre3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
