# Generated by Django 5.0.3 on 2024-03-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytabs', '0010_tab_genre_alter_tab_notation_alter_tab_tab_stems_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tab',
            name='level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
