# Generated by Django 5.0.3 on 2024-03-27 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytabs', '0011_tab_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mytabs.tab')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='favourite', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
